name: nextjs-ci

on:
  pull_request:
    branches: [main]
    paths: [blog/**]

jobs:
  nextjs-ci:
    name: nextjs-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./blog

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
    
    - name: Lint
      run: next lint --dir pages --dir components --dir lib --dir layouts --dir scripts