name: terraform-ci

on:
  pull_request:
    branches: [main]
    paths: [terraform/**]

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  terraform-ci:
    uses: mmccarthy404/reusable-workflows/.github/workflows/terraform-ci.yaml@v1.0.0
    with:
      terraform-version: 1.5.0
      terraform-directory: ./terraform
      terraform-var-file: terraform.tfvars
      terraform-backend-config: backend.tfvars
      aws-region: us-east-1
      aws-role: arn:aws:iam::004351562122:role/github-oidc-ahead-in-the-cloud
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}